### ISSUE TITLE
Prepare CodeBase for Contributors

### ISSUE THREAD

**Issue by hop-along-polly** [hop-along-polly/always-on#1]
There's so much to do here I'm not even sure I can write it all down. Basically I know what I need to do so the AlwaysON code base is ready for additional contributors.

**Comment by chrishalbert** [comment]
The healthcheck worked for me! A few things that come to mind for me:
- [ ] linter - maybe use black?
- [ ] github action to ensure lint and tests pass, and maybe a certain level of code coverage
- [x] maybe require code review by a maintainer (you) so that 1.) I cant run up your bill and 2.) I can't modify files to try and gain access to your secrets
- [x] Version Control Branching Strategy - should I create PR to main, or rel-v1, etc
- [x] Branch naming convention - should I name the branch chalbert/gh-1/contributor-md for instance?
- [ ] Canned PR Template - For example, short description, how to test, did you add tests, github issue reference

**Comment by hop-along-polly** [comment]
I pushed up some changes that add's a great deal more detail to the CONTRIBUTING.md file. Going to enfore branch protection on `main` and add a PR Template. The other's I was going to create tickets for and would be great starting tasks if you would like to tackle them.

**Comment by chrishalbert** [comment]
I'm really liking how the branching/merging strategy not only aligns w/ the type of change, but also with the version increment.
